In [46]:
import autograd.numpy as np
from autograd import grad, jacobian
import autograd.numpy.random as npr

from matplotlib import pyplot as plt
from matplotlib import pyplot, cm
from mpl_toolkits.mplot3d import Axes3D 
%matplotlib inline

In [ ]:
Num = 64
space = np.linspace(0, 1, Num)


In [ ]:
def f1(x):
#     Laplace equation
    return 0.

def analytic_solution1(x):
    return (1 / (np.exp(np.pi) - np.exp(-np.pi))) * np.sin(np.pi * x[0]) * (np.exp(np.pi * x[1]) - np.exp(-np.pi * x[1]))

def f2(x):
    return 1.
# Elliptic PDEs, Poisson’s equation,

def A(x):
    return x[1]*np.sin(np.pi * x[0])

def psy_trial(x, N):
    return A(x) + x[0] * (1 - x[0]) * x[1] * (1 - x[1]) * N

def loss(w, x):
    
    return loss_sum

In [27]:
import numpy as np
import tensorflow as tf

import PIL.Image
from io import BytesIO
from IPython.display import clear_output, Image, display

from sklearn import datasets
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import matplotlib.cm
from matplotlib import pyplot as plt
from matplotlib import pyplot, cm
from mpl_toolkits.mplot3d import Axes3D 
%matplotlib inline

In [28]:
def analytic_solution(x):
    return (1 / (np.exp(np.pi) - np.exp(-np.pi))) * \
            np.sin(np.pi * x[0]) * (np.exp(np.pi * x[1]) - np.exp(-np.pi * x[1]))

In [33]:
N = 64 # 64*64 = 4096

NY = 1 #one f
bias = 0.01

x_space = np.linspace(0, 1, N)

print(x_space.shape)

input_data = np.zeros((N*N, 1+2))

for i, x in enumerate(x_space):
    for j, y in enumerate(x_space):
        index = i*N+j
        input_data[index][0] = bias
        input_data[index][1] = x
        input_data[index][2] = y
# print(train_X)  

output_data = np.zeros((N*N, NY))
for i, t in enumerate(input_data):
        output_data[i] = analytic_solution([t[1],t[2]])
        
print(np.amax(output_data))
print(input_data.shape)
print(output_data.shape)

(64,)
0.999689182001
(4096, 3)
(4096, 1)


In [32]:
# surface = np.zeros((N, N))

# for i in range(len(x)):
#     for j in range(len(y)):
#         surface[i][j] =  analytic_solution([x[i], y[j]])
# #         print(surface[i][j] )


# # print(surface)
# print(surface.shape)

# print(np.amax(surface))

In [39]:
# im = plt.imshow(Z, origin='lower', vmax=abs(Z).max(), vmin=-abs(Z).max())
# plt.show()

# fig = plt.figure()
# ax = fig.gca(projection='3d')
# X1, X2 = np.meshgrid(x_space, x_space)
# surf1 = ax.plot_surface(X1, X2, output_data, rstride=1, cstride=1, cmap=cm.viridis, linewidth=0, antialiased=False)


# ax.set_xlim(0, 1)
# ax.set_ylim(0, 1)
# ax.set_zlim(0, 2)

# ax.set_xlabel('$x$')
# ax.set_ylabel('$y$');

In [40]:
a =1.
s = (a, a*a)
print(s)

(1.0, 1.0)


#Tenserflow
https://gist.github.com/vinhkhuc/e53a70f9e5c3f55852b0

In [72]:
import numpy as np
import tensorflow as tf

import PIL.Image
from io import BytesIO
from IPython.display import clear_output, Image, display

from sklearn import datasets
from sklearn.model_selection import train_test_split

import matplotlib.pyplot as plt
import matplotlib.cm
from matplotlib import pyplot as plt
from matplotlib import pyplot, cm
from mpl_toolkits.mplot3d import Axes3D 
%matplotlib inline

In [5]:
RANDOM_SEED = 42
tf.set_random_seed(RANDOM_SEED)

In [6]:
def init_weights(shape):
    return tf.Variable(tf.random_normal(shape, stddev=0.1))

In [7]:
def forwardprop(X, w_1, w_2):
    return tf.matmul(tf.nn.sigmoid(tf.matmul(X, w_1)), w_2)

In [10]:
N = 64
NY = 1 #one f
bias = 0.01

x_space = np.linspace(0, 1, N)

print(x_space.shape)

input_data = np.zeros((N*N, 1+2))

for i, x in enumerate(x_space):
    for j, y in enumerate(x_space):
        index = i*N+j
        input_data[index][0] = bias
        input_data[index][1] = x
        input_data[index][2] = y
# print(train_X)  

def analytic_solution(x):
    return (1 / (np.exp(np.pi) - np.exp(-np.pi))) * np.sin(np.pi * x[0]) * (np.exp(np.pi * x[1]) - np.exp(-np.pi * x[1]))

output_data = np.zeros((N*N, NY))
for i, t in enumerate(input_data):
        output_data[i] = analytic_solution([t[1],t[2]])
        
print(np.amax(output_data))
print(input_data.shape)
print(output_data.shape)

(64,)
0.999689182001
(4096, 3)
(4096, 1)


In [11]:
p = 5

train_X = input_data[:p]
test_X  = input_data[p:]
train_y = output_data[:p]
test_y  = output_data[p:]

print(train_X.shape)
print(test_X.shape)# train_X, test_X, train_y, test_y = get_iris_data()
print(train_y.shape)
print(test_y.shape)

(5, 3)
(4091, 3)
(5, 1)
(4091, 1)


In [17]:
print(train_X.shape)
print(train_y.shape)

# Layer's sizes
x_size = train_X.shape[1]   # Number of input nodes: 4 features and 1 bias
h_size = 256                # Number of hidden nodes
y_size = train_y.shape[1]   # Number of outcomes (3 iris flowers)

# Symbols
X = tf.placeholder("float", shape=[None, x_size])
y = tf.placeholder("float", shape=[None, y_size])

# Weight initializations
w_1 = init_weights((x_size, h_size))
w_2 = init_weights((h_size, y_size))

# Forward propagation
yhat    = forwardprop(X, w_1, w_2)
predict = tf.argmax(yhat, axis=1)

psi = tf.matmul(X[2],tf.sin(np.pi*X[1])) + tf.matmul(tf.matmul(X[1]*(1-X[1]),X[2]* (1-X[2]),yhat)

# Backward propagation
cost = tf.reduce_mean(tf.reduce_sum(tf.gradient(tf.gradient(psi,X[2]),X[2])+tf.gradient(tf.gradient(psi,X[1]),X[1])-0))
# cost    = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y, logits=yhat))
updates = tf.train.GradientDescentOptimizer(0.001).minimize(cost)

# Run SGD
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

for epoch in range(10):
    # Train with each example
    for i in range(len(train_X)):
        sess.run(updates, feed_dict={X: train_X[i: i + 1], y: train_y[i: i + 1]})
    
    
#     train_accuracy = np.mean(np.argmax(train_y, axis=1) == sess.run(predict, feed_dict={X: train_X, y: train_y}))
#     test_accuracy  = np.mean(np.argmax(test_y, axis=1)  == sess.run(predict, feed_dict={X: test_X, y: test_y}))

#     print("Epoch = %d, train accuracy = %.2f%%, test accuracy = %.2f%%"% (epoch + 1, 100. * train_accuracy, 100. * test_accuracy))

sess.close()

SyntaxError: invalid syntax (<ipython-input-17-38dff4ccdb4b>, line 25)

In [181]:
    train_X, test_X, train_y, test_y = get_iris_data()
    print(test_y)

[[ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [77]:
# sklearn
def get_iris_data():
    """ Read the iris data set and split them into training and test sets """
    iris   = datasets.load_iris()
    data   = iris["data"]
    target = iris["target"]

    # Prepend the column of 1s for bias
    N, M  = data.shape
    all_X = np.ones((N, M + 1))
    all_X[:, 1:] = data

    # Convert into one-hot vectors
    num_labels = len(np.unique(target))
    all_Y = np.eye(num_labels)[target]  # One liner trick!
    return train_test_split(all_X, all_Y, test_size=0.33, random_state=RANDOM_SEED)

In [174]:
    train_X, test_X, train_y, test_y = get_iris_data()

    # Layer's sizes
    x_size = train_X.shape[1]   # Number of input nodes: 4 features and 1 bias
    h_size = 256                # Number of hidden nodes
    y_size = train_y.shape[1]   # Number of outcomes (3 iris flowers)

    # Symbols
    X = tf.placeholder("float", shape=[None, x_size])
    y = tf.placeholder("float", shape=[None, y_size])

    # Weight initializations
    w_1 = init_weights((x_size, h_size))
    w_2 = init_weights((h_size, y_size))

    # Forward propagation
    yhat    = forwardprop(X, w_1, w_2)
    predict = tf.argmax(yhat, axis=1)

    # Backward propagation
    cost    = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y, logits=yhat))
    updates = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

    # Run SGD
    sess = tf.Session()
    init = tf.global_variables_initializer()
    sess.run(init)

    for epoch in range(100):
        # Train with each example
        for i in range(len(train_X)):
            sess.run(updates, feed_dict={X: train_X[i: i + 1], y: train_y[i: i + 1]})

        train_accuracy = np.mean(np.argmax(train_y, axis=1) ==
                                 sess.run(predict, feed_dict={X: train_X, y: train_y}))
        test_accuracy  = np.mean(np.argmax(test_y, axis=1) ==
                                 sess.run(predict, feed_dict={X: test_X, y: test_y}))

        print("Epoch = %d, train accuracy = %.2f%%, test accuracy = %.2f%%"
              % (epoch + 1, 100. * train_accuracy, 100. * test_accuracy))

    sess.close()

Epoch = 1, train accuracy = 62.00%, test accuracy = 70.00%
Epoch = 2, train accuracy = 65.00%, test accuracy = 70.00%
Epoch = 3, train accuracy = 65.00%, test accuracy = 70.00%
Epoch = 4, train accuracy = 68.00%, test accuracy = 70.00%
Epoch = 5, train accuracy = 70.00%, test accuracy = 70.00%
Epoch = 6, train accuracy = 71.00%, test accuracy = 74.00%
Epoch = 7, train accuracy = 72.00%, test accuracy = 78.00%
Epoch = 8, train accuracy = 78.00%, test accuracy = 78.00%
Epoch = 9, train accuracy = 81.00%, test accuracy = 78.00%
Epoch = 10, train accuracy = 83.00%, test accuracy = 78.00%
Epoch = 11, train accuracy = 86.00%, test accuracy = 78.00%
Epoch = 12, train accuracy = 87.00%, test accuracy = 78.00%
Epoch = 13, train accuracy = 87.00%, test accuracy = 80.00%
Epoch = 14, train accuracy = 87.00%, test accuracy = 82.00%
Epoch = 15, train accuracy = 88.00%, test accuracy = 82.00%
Epoch = 16, train accuracy = 88.00%, test accuracy = 84.00%
Epoch = 17, train accuracy = 89.00%, test accurac

In [44]:
def f(x1,x2):
    return (1 / (tf.exp(np.pi) - tf.exp(-np.pi))) * tf.sin(np.pi * x1) * (tf.exp(np.pi * x2) - tf.exp(-np.pi * x2))

# tf.reset_default_graph()
sess = tf.InteractiveSession()
x1 = tf.Variable(0, dtype = tf.float32, name = 'x1')
x2 = tf.Variable(0, dtype = tf.float32, name = 'x2')

objective = f(x1,x2)
optimizer = []
optimizer.append(tf.train.GradientDescentOptimizer(0.001).minimize(objective))

sess.run(tf.global_variables_initializer())

